version = 0.1

[default.global.parameters]
stack_name = "lambda-linkedin-finder"
region = "eu-central-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "eu-central-1"
parameter_overrides = "AppStage=\"dev\" EmailProvider=\"resend\" EmailFrom=\"LinkedIn Finder <onboarding@resend.dev>\" ReportEmailTo=\"dimitar@dimitar.ai\" JobKeywords=\"node.js,python,ai engineer,fullstack,react native,front-end\" JobLocation=\"Bulgaria\" LinkedInGeoId=\"105333783\" JobPostedWithin=\"r3600\" RunsTableName=\"dev-linkedin-finder-runs\""
s3_prefix = "lambda-linkedin-finder"
disable_rollback = true
image_repositories = []

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_invoke.parameters]
warm_containers = "EAGER"
